sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t neerajmaor/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true neerajmaor/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "web-react-apps"
  env: "Web-react-apps-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-336788888119"
  bucket_path: "web-react-apps"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
